config/routes.rb
Rails.application.routes.draw do
  # root :to => 'home#index'
  root :to => 'recurring#create_recurring_application_charge'
  mount ShopifyApp::Engine, at: '/'
  get 'index',to: 'home#index'
  get 'activatecharge',to: 'recurring#activate_charge'
  post '/cancel/charge',to: 'recurring#cancel_charge'
end

app/controllers/home_controller.rb
class HomeController < AuthenticatedController

  before_action :set_shop

  def index
    @shop = ShopifyAPI::Shop.current
    if params[:type].nil? || ( params[:type] == "unfulfilled" && params[:search].blank? )
      @active = "unfulfilled"
      @orders = ShopifyAPI::Order.find(:all, params: { limit: 2 ,status: 'any',fulfillment_status: 'unfulfilled' })
    elsif (params[:type] == "all" && params[:search].blank?)
      @orders = ShopifyAPI::Order.find(:all, params: { limit: 2 ,status: 'any' })
      @active = "all"
    end
    if params[:token]
      @orders = ShopifyAPI::Order.find(:all, params: { limit: 2,page_info: params[:token] })
    end
  end

  private

  def set_shop
    @current_shop = Shop.find_by_shopify_domain(session[:shopify_domain])
  end

end

app/views/home/_orders.html.erb
<div class = "order-append">
  <table id="example" class="table table-striped table-bordered table-sm" style="width: 1000px;">
    <thead>
      <tr>
        <th>Order</th>
        <th>Date</th>
        <th>Customer</th>
        <th>Payment</th>
        <th>Fulfillment</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order&.name, "https://#{@shop.myshopify_domain}/admin/orders/#{order.id}", target: "_blank" %></td>
          <td><%= order&.created_at.to_date.strftime('%b %d,%Y') %></td>
          <td><%= "#{order&.customer&.first_name} #{order&.customer&.last_name}" %></td>
          <td><%= order&.financial_status %></td>
          <td><%= order&.fulfillment_status ? order&.fulfillment_status : 'unfulfilled' %></td>
          <td><%= order&.total_price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('#example').DataTable({
      "paging": false,
      "searching": false,
      "lengthChange": false,
      "pageLength": 2,
      "columnDefs": [
        { "orderable": false, "targets": 3 },
        { "orderable": false, "targets": 4 },
        { "orderable": false, "targets": 5 },
        { "orderable": false, "targets": 6 }
      ]
    });
  });
</script>

app/views/home/index.html.erb
<h2>Cash On Delivery App</h2>
<div>
  <% unless @current_shop.charge_cancelled %>
    <%= link_to 'Cancel_charge',cancel_charge_path,method: 'post' %>
  <% end %>
</div>
<div>
  <%= link_to 'unfulfilled',index_path(type: 'unfulfilled'),id: 'unfulfill' %>
  <%= link_to 'All', index_path(type: 'all'),id: 'all' %>
</div>

<div class="container">
  <div class = "order">
    <%= render partial: 'orders' %>
  </div>
   <div class = "paging">
    <% if @orders.next_page? %>
      <%= link_to 'Next_page', index_path(token: @orders.next_page_info) %>
    <% end %>
    <% if @orders.previous_page? %>
      <%= link_to 'Prevous_page', index_path(token: @orders.previous_page_info ) %>
    <% end %>
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function(){
    var t = '';
    $("#search").keyup(function(e){
      clearTimeout(t);
      t = setTimeout(function () {
        form = document.querySelector('#search_form');
        form.dispatchEvent(new Event('submit', {bubbles: true}));
      }, 1000);
    });
  });
</script>

app/views/home/index.js.erb
$("#order-append").remove();
$(".order").html("<%= j render(partial: 'orders') %>");
if(!$("#search").val().length == 0){
  $(".paging").hide();
}else{
  $(".paging").show();
}